
def GetMembers(token : str, clan : str) -> list: ...
def GetPreviousRaidWeekend(token : str, clan : str) -> dict: ...
def GetPreviousClanWar(token : str, clan : str) -> list: ...
def GetClanInfo(token : str, clan : str) -> dict: ...
def GetPlayerInfo(token : str, playerTag : str) -> dict: ...
