import sqlite3

def GetMemberMessages(serverID : int, databaseFile : str) -> list: ...
def GetPrimaryClan(serverID : int, databaseFile : str) -> str: ...
def LinkClan(serverID : int, clanTag : str, databaseFile : str) -> bool: ...