import sqlite3

def GetMemberMessages(serverID : int, databaseFile : str) -> list: ...
def GetPrimaryClan(serverID : int, databaseFile : str) -> str: ...
def LinkClan(serverID : int, clanTag : str, databaseFile : str) -> bool: ...
def GetClanGamesParticipation(playerTag : str, databaseFile : str) -> bool: ...
def GetWarParticipation(playerTag : str, databaseFile : str) -> bool: ...
def GetClanGamesLastUpdate(playerTag : str) -> str: ...
def UpdateClanGamesInfo(playerTag : str, monthDiff : int) -> None: ...
def UpdateWarMark(playerTag : str, newState : bool) -> None: ...