from sqlite3 import Cursor, Connection

def tableVisualise(connectionSQL : Connection, table : str, print : bool = True) -> str: ... 
def advancedVisualise(fieldNames : list, resultData : list, print : bool = True) -> str: ...
def queryVisualise(cursorSQL : Cursor, query : str, *args, print : bool = True) -> str: ...
