async def OrderClanMembers(clanMemberDetails : dict, sortKeys : list) -> list: ...
async def GetLongest(*strs) -> str : ...
async def IsInt(item : str) -> bool: ...
def GetLeagueID(playerData : dict) -> str: ...
