async def OrderClanMembers(clanMemberDetails : dict, sortKeys : list) -> list: ...
async def GetLongest(*strs) -> str : ...
async def IsInt(item : str) -> bool: ...
def GetLeagueID(playerData : dict) -> str: ...
def CalculateLastClanGames(date : str) -> str: ...
def CalculateClanGamesBetween(updatedFor : str, lastClanGames : str) -> int: ...